### ISSUE TITLE
请求字段内容带对象时怎么处理？

### ISSUE THREAD

**Issue by jackhe16** [holyselina/egg-api-auth#1]
stringifyParams(params) {
    return Object.keys(params).sort().map(x => x + '=' + params[x])
      .join('&');
  },

**Comment by jackhe16** [comment]
stringifyParams(params) {
    return Object.keys(params).sort().map(x => {
      let value = params[x];
      if (typeof value === 'object') {
        value = JSON.stringify(value);
      }
      return x + '=' + value;
    })
      .join('&');
  },
是否可以改成这样，针对put post请求的ctx.body内可能存在的数组，对象进行JSON.stringify()

**Comment by holyselina** [comment]
加这个判断也处理不了文件上传的情况,可以根据需要覆盖stringifyParams 或者 validateSign 方法

**Comment by jackhe16** [comment]
好的谢谢
